{% set version = "0.0.9" %}

package:
  name: pyncml
  version: {{ version }}

source:
  fn: pyncml-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/pyncml/pyncml-{{ version }}.tar.gz
  sha256: f0df2ab0644e0f0923794db74cd55a23999f8c2889153bcdcd96ca27aeff4fac

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - netcdf4
    - pytz
  run:
    - python
    - numpy
    - netcdf4
    - pytz

test:
  imports:
    - pyncml

about:
  home: https://github.com/axiom-data-science/pyncml
  license: MIT
  license_file: LICENSE.txt
  summary: 'A simple python library to apply NcML logic to NetCDF files.'

extra:
  recipe-maintainers:
    - kwilcox
    - ocefpaf
