travis:
  secure:
    BINSTAR_TOKEN: rLBAWfDeAUhvLHqcdn7RtWfOlUDsoZSw8nRZyAbfLNDnZP2E0FqSAzBsObf7lnVK27Q3Yo7r7Mv/QKgIQlhFeXUqA5maAFpQwkDjlVvg5idqxjX3JKCW4vkqFXWToga/JjH8OL3qKxITA2oyLmjjrluHB3E4/RwwnqbiEekZuWUi7IuHtF1b0Bg3ECwIVpULyiT7fUWuIv5PFiUVu+dhtlEow5/HKvLTfXSGgzp//NAe+efKDh+JuAEN971LL7LTWmEm6AFxcqZKxb7miQTOySM9ujjiqsPocBwSfijabR2Z5MDvwcai6TPRjXUkHWQMnAtq/BvF1Zc0qZ9eqaOf0381C9T1X/EkXbV3mcBXunZhDlP5JFH45NWD6hR50hm58z0SZYV95mzdF9rK5Yl5xjN49mWE54qFAFW26LWN3IAuZrjeAheMJ4rcdoLYzHba0LCLldtJgZLOj9/3WEqPfoBs3/BSBSc1sHZfqr+AzVQ8SLv+HLkwwTPHUqexPOK9fttz9CCk1of8v0Whnm4ZURRC5tKJKbQv7IFxBb3+EIfIM1li1dJTNHpsWMZAR903jtxMfkqy/StJA00EUKquN8zSzaLdiZfLx9Cki2iwMr0nwQWgTeQWcssWGn4qB0L6TwHE+yMZ7hwSNysAF886vhvbYugXKVo4yncoaGN0cKw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
