travis:
  secure:
    BINSTAR_TOKEN: acMV3x+Oq0sagdJjr4L2Mx7cfUZ6gLMVbLw4rJM6Y6R0ibXtz1YgUwj04UGQc7F0p5KJwKCaHdedQ201aX8v2pLt73dCbJVs2DkXDT61sdAZs4XBSqR13/bymVkIOAXoU/Ajjm+tFcuyP/MILxEIymXkbj7qWeA4qp6H6uBZXPzCpreqo/yu1oYbhsZ2+FPQh6Ll30azxPxcJtkVmpt7JEceCykmxxSKiBqxgL9JHa6e1Wg2cnXpwwHRIWUccZqdnEXMNg8xiVn2Vp6ymSX2JcuaX3s7pI2Yti4ncC5vEaLbc9lLqjIjgy4SQ3qhnujLPYWQTkO1LaHdArM+mccJZvXJ/zuIvr+p2LCvUEg7ebmMVxPtX3hOoskwwc5zpg5AjWWAVJ0SEiCLoeh162OybsB5HZcnlRwoRAUY4BmvfEza+zuLL4P/MM3m6vujhGklx4hn5Aa431Mq6iw1dlcgDYyOisOG4fdgjr9PblJ/BYosnSpCYzGvyn0HTRw9SOaXl2g4fnMol3K70tzEJqI4Cb1a1BQ/gSyejmIuvjqLFtOsvmIoBgKkdOrR7z19Zp8fE8HxFVN9pjDyFMuyuJIaCeoh7F5eznK50VoKKjPg7F8roPR2Gt5wuo3me6j/z6Biv2cECq2oCdd9ysvSkMbMBDDY2FGoXn6nTuOmSalcg14=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
